"""empty message

Revision ID: ee14b3808344
Revises: 3cf442ce24f3
Create Date: 2023-02-22 08:52:44.967260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee14b3808344'
down_revision = '3cf442ce24f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('type_print', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('file_type'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prints_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'prints', ['prints_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prints_id')

    op.drop_table('prints')
    # ### end Alembic commands ###
